name: Deploy to aws
on: 
  push:
    branches:   
      - prod
      - dev
  pull_request:
    branches: 
      - prod
      - dev
  
  
jobs:
  automated_test:
    runs-on: ubuntu-latest
    steps:
      - name: Testscript
        run: |
          echo "Testscripts need to be defined and applied here"
          echo Pullrequest
          echo ${{ github.event.pull_request }}
          echo branche:
          echo ${{ github.ref }}
          echo eventName
          echo ${{ github.event_name }}


  test_prod_env:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Testscript
        run: |
          echo "Testscript when pushed to production"
          echo Pullrequest
          echo ${{ github.event.pull_request }}
          echo branche:
          echo ${{ github.ref }}
          echo eventName
          echo ${{ github.event_name }}